name: Update FIDO MDS Metadata

on:
  # Run weekly on Sundays at 2 AM UTC
  schedule:
    - cron: '0 2 * * 0'
  
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-mds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests PyJWT cryptography
    
    - name: Download and parse FIDO MDS
      run: |
        python .github/scripts/update_mds.py

    - name: Check for changes
      id: git-check
      run: |
        # List modified and untracked files (excluding .gitignored)
        CHANGED_FILES=$(git ls-files -m -o --exclude-standard)

        if [ -z "$CHANGED_FILES" ]; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          # Save the list for the commit step to stage only these files
          printf "%s\n" "$CHANGED_FILES" > changed_files.txt
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Stage only the changed files discovered earlier
        while IFS= read -r file; do
          git add -- "$file"
        done < changed_files.txt

        # Commit staged changes
        git commit -m "Update FIDO MDS metadata - $(date '+%Y-%m-%d %H:%M:%S UTC')"
        git push
    
    - name: Create summary comment
      if: steps.git-check.outputs.changes == 'true'
      run: |
        if [ -f mds_summary.json ]; then
          echo "## MDS Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "Updated on: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat mds_summary.json | python -m json.tool >> $GITHUB_STEP_SUMMARY
        fi
